LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
$(shell mkdir -p $(TARGET_OUT)/system/lib)
$(shell mkdir -p $(TARGET_OUT)/system/vendor)
$(shell cp -r $(LOCAL_PATH)/lib/* $(TARGET_OUT)/system/lib/)
$(shell cp -r $(LOCAL_PATH)/vendor/* $(TARGET_OUT)/system/vendor/)