PRODUCT_COPY_FILES += \
    vendor/samsung/santos10wifi/lib/libsoundtrigger.so:system/lib/libsoundtrigger.so \
    vendor/samsung/santos10wifi/lib/libRSDriver.so:system/lib/libRSDriver.so \
    vendor/samsung/santos10wifi/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/samsung/santos10wifi/lib/libOpenSLES.so:system/lib/libOpenSLES.so \
    vendor/samsung/santos10wifi/lib/libbcinfo.so:system/lib/libbcinfo.so \
    vendor/samsung/santos10wifi/lib/libclcore_debug.bc:system/lib/libclcore_debug.bc \
    vendor/samsung/santos10wifi/lib/libbinder.so:system/lib/libbinder.so \
    vendor/samsung/santos10wifi/lib/libRS.so:system/lib/libRS.so \
    vendor/samsung/santos10wifi/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
    vendor/samsung/santos10wifi/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/samsung/santos10wifi/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
    vendor/samsung/santos10wifi/lib/soundfx/libldnhncr.so:system/lib/soundfx/libldnhncr.so \
    vendor/samsung/santos10wifi/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
    vendor/samsung/santos10wifi/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
    vendor/samsung/santos10wifi/lib/soundfx/libeffectproxy.so:system/lib/soundfx/libeffectproxy.so \
    vendor/samsung/santos10wifi/lib/libOMXVideoDecoderMPEG4.so:system/lib/libOMXVideoDecoderMPEG4.so \
    vendor/samsung/santos10wifi/lib/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
    vendor/samsung/santos10wifi/lib/drm/libfwdlockengine.so:system/lib/drm/libfwdlockengine.so \
    vendor/samsung/santos10wifi/lib/libmdnssd.so:system/lib/libmdnssd.so \
    vendor/samsung/santos10wifi/lib/libpac.so:system/lib/libpac.so \
    vendor/samsung/santos10wifi/lib/content-types.properties:system/lib/content-types.properties \
    vendor/samsung/santos10wifi/lib/libdrmframework.so:system/lib/libdrmframework.so \
    vendor/samsung/santos10wifi/lib/libclcore_g.bc:system/lib/libclcore_g.bc \
    vendor/samsung/santos10wifi/lib/libart-compiler.so:system/lib/libart-compiler.so \
    vendor/samsung/santos10wifi/lib/libkeystore-engine.so:system/lib/libkeystore-engine.so \
    vendor/samsung/santos10wifi/lib/libgui.so:system/lib/libgui.so \
    vendor/samsung/santos10wifi/lib/libbase.so:system/lib/libbase.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_vpxenc.so:system/lib/libstagefright_soft_vpxenc.so \
    vendor/samsung/santos10wifi/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_avcenc.so:system/lib/libstagefright_soft_avcenc.so \
    vendor/samsung/santos10wifi/lib/libskia.so:system/lib/libskia.so \
    vendor/samsung/santos10wifi/lib/libssl.so:system/lib/libssl.so \
    vendor/samsung/santos10wifi/lib/libsoftkeymaster.so:system/lib/libsoftkeymaster.so \
    vendor/samsung/santos10wifi/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/samsung/santos10wifi/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/samsung/santos10wifi/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/samsung/santos10wifi/lib/hw/lights.clovertrail.so:system/lib/hw/lights.clovertrail.so \
    vendor/samsung/santos10wifi/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/samsung/santos10wifi/lib/hw/camera.santos10.so:system/lib/hw/camera.santos10.so \
    vendor/samsung/santos10wifi/lib/hw/power.clovertrail.so:system/lib/hw/power.clovertrail.so \
    vendor/samsung/santos10wifi/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/samsung/santos10wifi/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/samsung/santos10wifi/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/samsung/santos10wifi/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
    vendor/samsung/santos10wifi/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/samsung/santos10wifi/lib/hw/audio.hdmi.clovertrail.so:system/lib/hw/audio.hdmi.clovertrail.so \
    vendor/samsung/santos10wifi/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
    vendor/samsung/santos10wifi/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so \
    vendor/samsung/santos10wifi/lib/hw/sensors.santos10.so:system/lib/hw/sensors.santos10.so \
    vendor/samsung/santos10wifi/lib/hw/consumerir.clovertrail.so:system/lib/hw/consumerir.clovertrail.so \
    vendor/samsung/santos10wifi/lib/hw/audio.primary.clovertrail.so:system/lib/hw/audio.primary.clovertrail.so \
    vendor/samsung/santos10wifi/lib/libopus.so:system/lib/libopus.so \
    vendor/samsung/santos10wifi/lib/libsparse.so:system/lib/libsparse.so \
    vendor/samsung/santos10wifi/lib/libinputflinger.so:system/lib/libinputflinger.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_mpeg4dec.so:system/lib/libstagefright_soft_mpeg4dec.so \
    vendor/samsung/santos10wifi/lib/libntfs-3g.so:system/lib/libntfs-3g.so \
    vendor/samsung/santos10wifi/lib/libext2fs.so:system/lib/libext2fs.so \
    vendor/samsung/santos10wifi/lib/libbacktrace.so:system/lib/libbacktrace.so \
    vendor/samsung/santos10wifi/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/santos10wifi/lib/libharfbuzz_ng.so:system/lib/libharfbuzz_ng.so \
    vendor/samsung/santos10wifi/lib/libgabi++.so:system/lib/libgabi++.so \
    vendor/samsung/santos10wifi/lib/libinput.so:system/lib/libinput.so \
    vendor/samsung/santos10wifi/lib/pvr_drv_video.so:system/lib/pvr_drv_video.so \
    vendor/samsung/santos10wifi/lib/libsonivox.so:system/lib/libsonivox.so \
    vendor/samsung/santos10wifi/lib/libstagefright_avc_common.so:system/lib/libstagefright_avc_common.so \
    vendor/samsung/santos10wifi/lib/libusbhost.so:system/lib/libusbhost.so \
    vendor/samsung/santos10wifi/lib/libext2_com_err.so:system/lib/libext2_com_err.so \
    vendor/samsung/santos10wifi/lib/libjni_latinimegoogle.so:system/lib/libjni_latinimegoogle.so \
    vendor/samsung/santos10wifi/lib/libwrs_omxil_core_pvwrapped.so:system/lib/libwrs_omxil_core_pvwrapped.so \
    vendor/samsung/santos10wifi/lib/libext2_profile.so:system/lib/libext2_profile.so \
    vendor/samsung/santos10wifi/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/santos10wifi/lib/libmemtrack.so:system/lib/libmemtrack.so \
    vendor/samsung/santos10wifi/lib/libttspico.so:system/lib/libttspico.so \
    vendor/samsung/santos10wifi/lib/libhardware.so:system/lib/libhardware.so \
    vendor/samsung/santos10wifi/lib/libfilterpack_imageproc.so:system/lib/libfilterpack_imageproc.so \
    vendor/samsung/santos10wifi/lib/lib7z.so:system/lib/lib7z.so \
    vendor/samsung/santos10wifi/lib/libnetdaidl.so:system/lib/libnetdaidl.so \
    vendor/samsung/santos10wifi/lib/libpdfium.so:system/lib/libpdfium.so \
    vendor/samsung/santos10wifi/lib/libjavacrypto.so:system/lib/libjavacrypto.so \
    vendor/samsung/santos10wifi/lib/libc++.so:system/lib/libc++.so \
    vendor/samsung/santos10wifi/lib/libvixl.so:system/lib/libvixl.so \
    vendor/samsung/santos10wifi/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
    vendor/samsung/santos10wifi/lib/libaudiospdif.so:system/lib/libaudiospdif.so \
    vendor/samsung/santos10wifi/lib/libpowermanager.so:system/lib/libpowermanager.so \
    vendor/samsung/santos10wifi/lib/libaudiopolicyservice.so:system/lib/libaudiopolicyservice.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_hevcdec.so:system/lib/libstagefright_soft_hevcdec.so \
    vendor/samsung/santos10wifi/lib/libjni_jpegutil.so:system/lib/libjni_jpegutil.so \
    vendor/samsung/santos10wifi/lib/libcrypto_utils.so:system/lib/libcrypto_utils.so \
    vendor/samsung/santos10wifi/lib/libOMXVideoEncoderAVC.so:system/lib/libOMXVideoEncoderAVC.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_mpeg2dec.so:system/lib/libstagefright_soft_mpeg2dec.so \
    vendor/samsung/santos10wifi/lib/libpiex.so:system/lib/libpiex.so \
    vendor/samsung/santos10wifi/lib/libOMXVideoDecoderAVC.so:system/lib/libOMXVideoDecoderAVC.so \
    vendor/samsung/santos10wifi/lib/libpcre.so:system/lib/libpcre.so \
    vendor/samsung/santos10wifi/lib/libintelmetadatabuffer.so:system/lib/libintelmetadatabuffer.so \
    vendor/samsung/santos10wifi/lib/libwsbm.so:system/lib/libwsbm.so \
    vendor/samsung/santos10wifi/lib/libstagefright_http_support.so:system/lib/libstagefright_http_support.so \
    vendor/samsung/santos10wifi/lib/libandroid_servers.so:system/lib/libandroid_servers.so \
    vendor/samsung/santos10wifi/lib/libext2_uuid.so:system/lib/libext2_uuid.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_vorbisdec.so:system/lib/libstagefright_soft_vorbisdec.so \
    vendor/samsung/santos10wifi/lib/libva-android.so:system/lib/libva-android.so \
    vendor/samsung/santos10wifi/lib/libvulkan.so:system/lib/libvulkan.so \
    vendor/samsung/santos10wifi/lib/libf2fs.so:system/lib/libf2fs.so \
    vendor/samsung/santos10wifi/lib/libpower.so:system/lib/libpower.so \
    vendor/samsung/santos10wifi/lib/libext2_quota.so:system/lib/libext2_quota.so \
    vendor/samsung/santos10wifi/lib/libstagefright.so:system/lib/libstagefright.so \
    vendor/samsung/santos10wifi/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/samsung/santos10wifi/lib/libhoudini.so:system/lib/libhoudini.so \
    vendor/samsung/santos10wifi/lib/libcamera2ndk.so:system/lib/libcamera2ndk.so \
    vendor/samsung/santos10wifi/lib/libshim_drm.so:system/lib/libshim_drm.so \
    vendor/samsung/santos10wifi/lib/libFFTEm.so:system/lib/libFFTEm.so \
    vendor/samsung/santos10wifi/lib/libclcore.bc:system/lib/libclcore.bc \
    vendor/samsung/santos10wifi/lib/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/samsung/santos10wifi/lib/libwebviewchromium_loader.so:system/lib/libwebviewchromium_loader.so \
    vendor/samsung/santos10wifi/lib/libexpat.so:system/lib/libexpat.so \
    vendor/samsung/santos10wifi/lib/libmemunreachable.so:system/lib/libmemunreachable.so \
    vendor/samsung/santos10wifi/lib/libcrypto.so:system/lib/libcrypto.so \
    vendor/samsung/santos10wifi/lib/libOpenMAXAL.so:system/lib/libOpenMAXAL.so \
    vendor/samsung/santos10wifi/lib/libsigchain.so:system/lib/libsigchain.so \
    vendor/samsung/santos10wifi/lib/libaudioroute.so:system/lib/libaudioroute.so \
    vendor/samsung/santos10wifi/lib/libjnigraphics.so:system/lib/libjnigraphics.so \
    vendor/samsung/santos10wifi/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/samsung/santos10wifi/lib/libdiskconfig.so:system/lib/libdiskconfig.so \
    vendor/samsung/santos10wifi/lib/libdrm.so:system/lib/libdrm.so \
    vendor/samsung/santos10wifi/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
    vendor/samsung/santos10wifi/lib/libwpa_client.so:system/lib/libwpa_client.so \
    vendor/samsung/santos10wifi/lib/libmtp.so:system/lib/libmtp.so \
    vendor/samsung/santos10wifi/lib/libaudiopolicyenginedefault.so:system/lib/libaudiopolicyenginedefault.so \
    vendor/samsung/santos10wifi/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/santos10wifi/lib/liblogwrap.so:system/lib/liblogwrap.so \
    vendor/samsung/santos10wifi/lib/libext2_e2p.so:system/lib/libext2_e2p.so \
    vendor/samsung/santos10wifi/lib/libcorkscrew.so:system/lib/libcorkscrew.so \
    vendor/samsung/santos10wifi/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
    vendor/samsung/santos10wifi/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
    vendor/samsung/santos10wifi/lib/libLLVM.so:system/lib/libLLVM.so \
    vendor/samsung/santos10wifi/lib/libjni_gallery_eglfence.so:system/lib/libjni_gallery_eglfence.so \
    vendor/samsung/santos10wifi/lib/libnfc_ndef.so:system/lib/libnfc_ndef.so \
    vendor/samsung/santos10wifi/lib/libf2fs_sparseblock.so:system/lib/libf2fs_sparseblock.so \
    vendor/samsung/santos10wifi/lib/libnl.so:system/lib/libnl.so \
    vendor/samsung/santos10wifi/lib/libmediaextractorservice.so:system/lib/libmediaextractorservice.so \
    vendor/samsung/santos10wifi/lib/libaudiopolicymanager.so:system/lib/libaudiopolicymanager.so \
    vendor/samsung/santos10wifi/lib/libclcore_x86.bc:system/lib/libclcore_x86.bc \
    vendor/samsung/santos10wifi/lib/crtbegin_so.o:system/lib/crtbegin_so.o \
    vendor/samsung/santos10wifi/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    vendor/samsung/santos10wifi/lib/libOMXVideoDecoderH263.so:system/lib/libOMXVideoDecoderH263.so \
    vendor/samsung/santos10wifi/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/samsung/santos10wifi/lib/libva.so:system/lib/libva.so \
    vendor/samsung/santos10wifi/lib/libui.so:system/lib/libui.so \
    vendor/samsung/santos10wifi/lib/libaudioresampler.so:system/lib/libaudioresampler.so \
    vendor/samsung/santos10wifi/lib/libttscompat.so:system/lib/libttscompat.so \
    vendor/samsung/santos10wifi/lib/libchrome.so:system/lib/libchrome.so \
    vendor/samsung/santos10wifi/lib/libwrs_omxil_common.so:system/lib/libwrs_omxil_common.so \
    vendor/samsung/santos10wifi/lib/libbluetooth_jni.so:system/lib/libbluetooth_jni.so \
    vendor/samsung/santos10wifi/lib/libnativebridge.so:system/lib/libnativebridge.so \
    vendor/samsung/santos10wifi/lib/libaudioutils.so:system/lib/libaudioutils.so \
    vendor/samsung/santos10wifi/lib/libpixelflinger.so:system/lib/libpixelflinger.so \
    vendor/samsung/santos10wifi/lib/libmediautils.so:system/lib/libmediautils.so \
    vendor/samsung/santos10wifi/lib/libdrmframework_jni.so:system/lib/libdrmframework_jni.so \
    vendor/samsung/santos10wifi/lib/libcutils.so:system/lib/libcutils.so \
    vendor/samsung/santos10wifi/lib/libstagefright_yuv.so:system/lib/libstagefright_yuv.so \
    vendor/samsung/santos10wifi/lib/libbinary_parse.so:system/lib/libbinary_parse.so \
    vendor/samsung/santos10wifi/lib/libselinux.so:system/lib/libselinux.so \
    vendor/samsung/santos10wifi/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
    vendor/samsung/santos10wifi/lib/libdefcontainer_jni.so:system/lib/libdefcontainer_jni.so \
    vendor/samsung/santos10wifi/lib/libandroidfw.so:system/lib/libandroidfw.so \
    vendor/samsung/santos10wifi/lib/libunwind.so:system/lib/libunwind.so \
    vendor/samsung/santos10wifi/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/samsung/santos10wifi/lib/libRSSupport.so:system/lib/libRSSupport.so \
    vendor/samsung/santos10wifi/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
    vendor/samsung/santos10wifi/lib/libc_malloc_debug.so:system/lib/libc_malloc_debug.so \
    vendor/samsung/santos10wifi/lib/libril.so:system/lib/libril.so \
    vendor/samsung/santos10wifi/lib/libradio_metadata.so:system/lib/libradio_metadata.so \
    vendor/samsung/santos10wifi/lib/libjavacore.so:system/lib/libjavacore.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_vpxdec.so:system/lib/libstagefright_soft_vpxdec.so \
    vendor/samsung/santos10wifi/lib/libva_videodecoder.so:system/lib/libva_videodecoder.so \
    vendor/samsung/santos10wifi/lib/libstagefright_httplive.so:system/lib/libstagefright_httplive.so \
    vendor/samsung/santos10wifi/lib/libtiff_directory.so:system/lib/libtiff_directory.so \
    vendor/samsung/santos10wifi/lib/libprocessgroup.so:system/lib/libprocessgroup.so \
    vendor/samsung/santos10wifi/lib/liblzma.so:system/lib/liblzma.so \
    vendor/samsung/santos10wifi/lib/libnativeloader.so:system/lib/libnativeloader.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_flacenc.so:system/lib/libstagefright_soft_flacenc.so \
    vendor/samsung/santos10wifi/lib/libmediacodecservice.so:system/lib/libmediacodecservice.so \
    vendor/samsung/santos10wifi/lib/libnetlink.so:system/lib/libnetlink.so \
    vendor/samsung/santos10wifi/lib/libicui18n.so:system/lib/libicui18n.so \
    vendor/samsung/santos10wifi/lib/libext2_blkid.so:system/lib/libext2_blkid.so \
    vendor/samsung/santos10wifi/lib/libappfuse_jni.so:system/lib/libappfuse_jni.so \
    vendor/samsung/santos10wifi/lib/libva-tpi.so:system/lib/libva-tpi.so \
    vendor/samsung/santos10wifi/lib/libmedia_jni.so:system/lib/libmedia_jni.so \
    vendor/samsung/santos10wifi/lib/libstdc++.so:system/lib/libstdc++.so \
    vendor/samsung/santos10wifi/lib/libstagefright_amrnb_common.so:system/lib/libstagefright_amrnb_common.so \
    vendor/samsung/santos10wifi/lib/libshim_gps.so:system/lib/libshim_gps.so \
    vendor/samsung/santos10wifi/lib/libshim_mds.so:system/lib/libshim_mds.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_gsmdec.so:system/lib/libstagefright_soft_gsmdec.so \
    vendor/samsung/santos10wifi/lib/libandroid.so:system/lib/libandroid.so \
    vendor/samsung/santos10wifi/lib/libiprouteutil.so:system/lib/libiprouteutil.so \
    vendor/samsung/santos10wifi/lib/libgatekeeper.so:system/lib/libgatekeeper.so \
    vendor/samsung/santos10wifi/lib/libopenjdk.so:system/lib/libopenjdk.so \
    vendor/samsung/santos10wifi/lib/libRS_internal.so:system/lib/libRS_internal.so \
    vendor/samsung/santos10wifi/lib/libmediadrm.so:system/lib/libmediadrm.so \
    vendor/samsung/santos10wifi/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/santos10wifi/lib/libwifi-service.so:system/lib/libwifi-service.so \
    vendor/samsung/santos10wifi/lib/liblog.so:system/lib/liblog.so \
    vendor/samsung/santos10wifi/lib/libblasV8.so:system/lib/libblasV8.so \
    vendor/samsung/santos10wifi/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/santos10wifi/lib/libGLESv3.so:system/lib/libGLESv3.so \
    vendor/samsung/santos10wifi/lib/libmedia.so:system/lib/libmedia.so \
    vendor/samsung/santos10wifi/lib/libopenjdkjvm.so:system/lib/libopenjdkjvm.so \
    vendor/samsung/santos10wifi/lib/libdl.so:system/lib/libdl.so \
    vendor/samsung/santos10wifi/lib/libvorbisidec.so:system/lib/libvorbisidec.so \
    vendor/samsung/santos10wifi/lib/libsync.so:system/lib/libsync.so \
    vendor/samsung/santos10wifi/lib/libsysutils.so:system/lib/libsysutils.so \
    vendor/samsung/santos10wifi/lib/libsoundpool.so:system/lib/libsoundpool.so \
    vendor/samsung/santos10wifi/lib/libnetutils.so:system/lib/libnetutils.so \
    vendor/samsung/santos10wifi/lib/libevent.so:system/lib/libevent.so \
    vendor/samsung/santos10wifi/lib/libm.so:system/lib/libm.so \
    vendor/samsung/santos10wifi/lib/libncurses.so:system/lib/libncurses.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_g711dec.so:system/lib/libstagefright_soft_g711dec.so \
    vendor/samsung/santos10wifi/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/santos10wifi/lib/libblas.so:system/lib/libblas.so \
    vendor/samsung/santos10wifi/lib/libicuuc.so:system/lib/libicuuc.so \
    vendor/samsung/santos10wifi/lib/libsonic.so:system/lib/libsonic.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_opusdec.so:system/lib/libstagefright_soft_opusdec.so \
    vendor/samsung/santos10wifi/lib/libminikin.so:system/lib/libminikin.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_amrdec.so:system/lib/libstagefright_soft_amrdec.so \
    vendor/samsung/santos10wifi/lib/libEGL.so:system/lib/libEGL.so \
    vendor/samsung/santos10wifi/lib/libRScpp.so:system/lib/libRScpp.so \
    vendor/samsung/santos10wifi/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/samsung/santos10wifi/lib/libmediandk.so:system/lib/libmediandk.so \
    vendor/samsung/santos10wifi/lib/libpcrecpp.so:system/lib/libpcrecpp.so \
    vendor/samsung/santos10wifi/lib/libkeymaster_messages.so:system/lib/libkeymaster_messages.so \
    vendor/samsung/santos10wifi/lib/libwilhelm.so:system/lib/libwilhelm.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_aacenc.so:system/lib/libstagefright_soft_aacenc.so \
    vendor/samsung/santos10wifi/lib/libc.so:system/lib/libc.so \
    vendor/samsung/santos10wifi/lib/libcap.so:system/lib/libcap.so \
    vendor/samsung/santos10wifi/lib/crtend_so.o:system/lib/crtend_so.o \
    vendor/samsung/santos10wifi/lib/libjni_terminal.so:system/lib/libjni_terminal.so \
    vendor/samsung/santos10wifi/lib/libsuspend.so:system/lib/libsuspend.so \
    vendor/samsung/santos10wifi/lib/libft2.so:system/lib/libft2.so \
    vendor/samsung/santos10wifi/lib/libfuse.so:system/lib/libfuse.so \
    vendor/samsung/santos10wifi/lib/librs_jni.so:system/lib/librs_jni.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_amrnbenc.so:system/lib/libstagefright_soft_amrnbenc.so \
    vendor/samsung/santos10wifi/lib/libpagemap.so:system/lib/libpagemap.so \
    vendor/samsung/santos10wifi/lib/libstlport.so:system/lib/libstlport.so \
    vendor/samsung/santos10wifi/lib/libminijail.so:system/lib/libminijail.so \
    vendor/samsung/santos10wifi/lib/libjpeg.so:system/lib/libjpeg.so \
    vendor/samsung/santos10wifi/lib/libutils.so:system/lib/libutils.so \
    vendor/samsung/santos10wifi/lib/libz.so:system/lib/libz.so \
    vendor/samsung/santos10wifi/lib/libandroid_runtime.so:system/lib/libandroid_runtime.so \
    vendor/samsung/santos10wifi/lib/libsoundtriggerservice.so:system/lib/libsoundtriggerservice.so \
    vendor/samsung/santos10wifi/lib/libprotobuf-cpp-lite.so:system/lib/libprotobuf-cpp-lite.so \
    vendor/samsung/santos10wifi/lib/libeffects.so:system/lib/libeffects.so \
    vendor/samsung/santos10wifi/lib/libnativehelper.so:system/lib/libnativehelper.so \
    vendor/samsung/santos10wifi/lib/libexfat.so:system/lib/libexfat.so \
    vendor/samsung/santos10wifi/lib/libstagefright_wfd.so:system/lib/libstagefright_wfd.so \
    vendor/samsung/santos10wifi/lib/libart-disassembler.so:system/lib/libart-disassembler.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_rawdec.so:system/lib/libstagefright_soft_rawdec.so \
    vendor/samsung/santos10wifi/lib/libETC1.so:system/lib/libETC1.so \
    vendor/samsung/santos10wifi/lib/libradioservice.so:system/lib/libradioservice.so \
    vendor/samsung/santos10wifi/lib/libshim_camera.so:system/lib/libshim_camera.so \
    vendor/samsung/santos10wifi/lib/libcmaudio_jni.so:system/lib/libcmaudio_jni.so \
    vendor/samsung/santos10wifi/lib/libimg_utils.so:system/lib/libimg_utils.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_avcdec.so:system/lib/libstagefright_soft_avcdec.so \
    vendor/samsung/santos10wifi/lib/libresourcemanagerservice.so:system/lib/libresourcemanagerservice.so \
    vendor/samsung/santos10wifi/lib/libext4_utils.so:system/lib/libext4_utils.so \
    vendor/samsung/santos10wifi/lib/libwebviewchromium_plat_support.so:system/lib/libwebviewchromium_plat_support.so \
    vendor/samsung/santos10wifi/lib/libbcc.so:system/lib/libbcc.so \
    vendor/samsung/santos10wifi/lib/libssh.so:system/lib/libssh.so \
    vendor/samsung/santos10wifi/lib/libjni_tinyplanet.so:system/lib/libjni_tinyplanet.so \
    vendor/samsung/santos10wifi/lib/libjni_pacprocessor.so:system/lib/libjni_pacprocessor.so \
    vendor/samsung/santos10wifi/lib/libprintspooler_jni.so:system/lib/libprintspooler_jni.so \
    vendor/samsung/santos10wifi/lib/libspeexresampler.so:system/lib/libspeexresampler.so \
    vendor/samsung/santos10wifi/lib/libserviceutility.so:system/lib/libserviceutility.so \
    vendor/samsung/santos10wifi/lib/libfilterfw.so:system/lib/libfilterfw.so \
    vendor/samsung/santos10wifi/lib/liblz4.so:system/lib/liblz4.so \
    vendor/samsung/santos10wifi/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/samsung/santos10wifi/lib/librsjni.so:system/lib/librsjni.so \
    vendor/samsung/santos10wifi/lib/libdng_sdk.so:system/lib/libdng_sdk.so \
    vendor/samsung/santos10wifi/lib/libjni_gallery_filters.so:system/lib/libjni_gallery_filters.so \
    vendor/samsung/santos10wifi/lib/libkeymaster1.so:system/lib/libkeymaster1.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_aacdec.so:system/lib/libstagefright_soft_aacdec.so \
    vendor/samsung/santos10wifi/lib/libpng.so:system/lib/libpng.so \
    vendor/samsung/santos10wifi/lib/libstagefright_enc_common.so:system/lib/libstagefright_enc_common.so \
    vendor/samsung/santos10wifi/lib/libart.so:system/lib/libart.so \
    vendor/samsung/santos10wifi/lib/libhwui.so:system/lib/libhwui.so \
    vendor/samsung/santos10wifi/lib/libva_videoencoder.so:system/lib/libva_videoencoder.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_mp3dec.so:system/lib/libstagefright_soft_mp3dec.so \
    vendor/samsung/santos10wifi/lib/libradio.so:system/lib/libradio.so \
    vendor/samsung/santos10wifi/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/samsung/santos10wifi/lib/libexif.so:system/lib/libexif.so \
    vendor/samsung/santos10wifi/lib/libsqlite.so:system/lib/libsqlite.so \
    vendor/samsung/santos10wifi/lib/libbacktrace_test.so:system/lib/libbacktrace_test.so \
    vendor/samsung/santos10wifi/lib/libkeystore_binder.so:system/lib/libkeystore_binder.so \
    vendor/samsung/santos10wifi/lib/libaudiopolicymanagerdefault.so:system/lib/libaudiopolicymanagerdefault.so \
    vendor/samsung/santos10wifi/lib/arm/libsoundtrigger.so:system/lib/arm/libsoundtrigger.so \
    vendor/samsung/santos10wifi/lib/arm/libRSDriver.so:system/lib/arm/libRSDriver.so \
    vendor/samsung/santos10wifi/lib/arm/libstagefright_omx.so:system/lib/arm/libstagefright_omx.so \
    vendor/samsung/santos10wifi/lib/arm/libOpenSLES.so:system/lib/arm/libOpenSLES.so \
    vendor/samsung/santos10wifi/lib/arm/libbcinfo.so:system/lib/arm/libbcinfo.so \
    vendor/samsung/santos10wifi/lib/arm/libbinder.so:system/lib/arm/libbinder.so \
    vendor/samsung/santos10wifi/lib/arm/libRS.so:system/lib/arm/libRS.so \
    vendor/samsung/santos10wifi/lib/arm/libdrmframework.so:system/lib/arm/libdrmframework.so \
    vendor/samsung/santos10wifi/lib/arm/libgui.so:system/lib/arm/libgui.so \
    vendor/samsung/santos10wifi/lib/arm/libbase.so:system/lib/arm/libbase.so \
    vendor/samsung/santos10wifi/lib/arm/libhardware_legacy.so:system/lib/arm/libhardware_legacy.so \
    vendor/samsung/santos10wifi/lib/arm/libskia.so:system/lib/arm/libskia.so \
    vendor/samsung/santos10wifi/lib/arm/libssl.so:system/lib/arm/libssl.so \
    vendor/samsung/santos10wifi/lib/arm/libopus.so:system/lib/arm/libopus.so \
    vendor/samsung/santos10wifi/lib/arm/libinputflinger.so:system/lib/arm/libinputflinger.so \
    vendor/samsung/santos10wifi/lib/arm/libbacktrace.so:system/lib/arm/libbacktrace.so \
    vendor/samsung/santos10wifi/lib/arm/libharfbuzz_ng.so:system/lib/arm/libharfbuzz_ng.so \
    vendor/samsung/santos10wifi/lib/arm/libgabi++.so:system/lib/arm/libgabi++.so \
    vendor/samsung/santos10wifi/lib/arm/libinput.so:system/lib/arm/libinput.so \
    vendor/samsung/santos10wifi/lib/arm/libsonivox.so:system/lib/arm/libsonivox.so \
    vendor/samsung/santos10wifi/lib/arm/libstagefright_avc_common.so:system/lib/arm/libstagefright_avc_common.so \
    vendor/samsung/santos10wifi/lib/arm/libusbhost.so:system/lib/arm/libusbhost.so \
    vendor/samsung/santos10wifi/lib/arm/libmemtrack.so:system/lib/arm/libmemtrack.so \
    vendor/samsung/santos10wifi/lib/arm/libhardware.so:system/lib/arm/libhardware.so \
    vendor/samsung/santos10wifi/lib/arm/libfilterpack_imageproc.so:system/lib/arm/libfilterpack_imageproc.so \
    vendor/samsung/santos10wifi/lib/arm/cpuinfo:system/lib/arm/cpuinfo \
    vendor/samsung/santos10wifi/lib/arm/libpdfium.so:system/lib/arm/libpdfium.so \
    vendor/samsung/santos10wifi/lib/arm/libc++.so:system/lib/arm/libc++.so \
    vendor/samsung/santos10wifi/lib/arm/libGLES_trace.so:system/lib/arm/libGLES_trace.so \
    vendor/samsung/santos10wifi/lib/arm/libaudiospdif.so:system/lib/arm/libaudiospdif.so \
    vendor/samsung/santos10wifi/lib/arm/libpowermanager.so:system/lib/arm/libpowermanager.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libOpenSLES.so:system/lib/arm/nb/libOpenSLES.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libbinder.so:system/lib/arm/nb/libbinder.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libgui.so:system/lib/arm/nb/libgui.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libhardware_legacy.so:system/lib/arm/nb/libhardware_legacy.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libskia.so:system/lib/arm/nb/libskia.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libhardware.so:system/lib/arm/nb/libhardware.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libpcre.so:system/lib/arm/nb/libpcre.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libstagefright.so:system/lib/arm/nb/libstagefright.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libGLESv2.so:system/lib/arm/nb/libGLESv2.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libOpenMAXAL.so:system/lib/arm/nb/libOpenMAXAL.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libjnigraphics.so:system/lib/arm/nb/libjnigraphics.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libsurfaceflinger.so:system/lib/arm/nb/libsurfaceflinger.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libui.so:system/lib/arm/nb/libui.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libpixelflinger.so:system/lib/arm/nb/libpixelflinger.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libcutils.so:system/lib/arm/nb/libcutils.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libaudioflinger.so:system/lib/arm/nb/libaudioflinger.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libicui18n.so:system/lib/arm/nb/libicui18n.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libandroid.so:system/lib/arm/nb/libandroid.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libGLESv3.so:system/lib/arm/nb/libGLESv3.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libmedia.so:system/lib/arm/nb/libmedia.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libdl.so:system/lib/arm/nb/libdl.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libm.so:system/lib/arm/nb/libm.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libicuuc.so:system/lib/arm/nb/libicuuc.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libEGL.so:system/lib/arm/nb/libEGL.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libGLESv1_CM.so:system/lib/arm/nb/libGLESv1_CM.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libmediandk.so:system/lib/arm/nb/libmediandk.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libc.so:system/lib/arm/nb/libc.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libft2.so:system/lib/arm/nb/libft2.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libutils.so:system/lib/arm/nb/libutils.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libz.so:system/lib/arm/nb/libz.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libandroid_runtime.so:system/lib/arm/nb/libandroid_runtime.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libnativehelper.so:system/lib/arm/nb/libnativehelper.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libcamera_client.so:system/lib/arm/nb/libcamera_client.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libart.so:system/lib/arm/nb/libart.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libhwui.so:system/lib/arm/nb/libhwui.so \
    vendor/samsung/santos10wifi/lib/arm/nb/libsqlite.so:system/lib/arm/nb/libsqlite.so \
    vendor/samsung/santos10wifi/lib/arm/libpcre.so:system/lib/arm/libpcre.so \
    vendor/samsung/santos10wifi/lib/arm/libstagefright_http_support.so:system/lib/arm/libstagefright_http_support.so \
    vendor/samsung/santos10wifi/lib/arm/libstagefright.so:system/lib/arm/libstagefright.so \
    vendor/samsung/santos10wifi/lib/arm/libGLESv2.so:system/lib/arm/libGLESv2.so \
    vendor/samsung/santos10wifi/lib/arm/libcommon_time_client.so:system/lib/arm/libcommon_time_client.so \
    vendor/samsung/santos10wifi/lib/arm/libFFTEm.so:system/lib/arm/libFFTEm.so \
    vendor/samsung/santos10wifi/lib/arm/libexpat.so:system/lib/arm/libexpat.so \
    vendor/samsung/santos10wifi/lib/arm/libemoji.so:system/lib/arm/libemoji.so \
    vendor/samsung/santos10wifi/lib/arm/libcrypto.so:system/lib/arm/libcrypto.so \
    vendor/samsung/santos10wifi/lib/arm/libOpenMAXAL.so:system/lib/arm/libOpenMAXAL.so \
    vendor/samsung/santos10wifi/lib/arm/libsigchain.so:system/lib/arm/libsigchain.so \
    vendor/samsung/santos10wifi/lib/arm/libjnigraphics.so:system/lib/arm/libjnigraphics.so \
    vendor/samsung/santos10wifi/lib/arm/libsurfaceflinger.so:system/lib/arm/libsurfaceflinger.so \
    vendor/samsung/santos10wifi/lib/arm/libLLVM.so:system/lib/arm/libLLVM.so \
    vendor/samsung/santos10wifi/lib/arm/libnfc_ndef.so:system/lib/arm/libnfc_ndef.so \
    vendor/samsung/santos10wifi/lib/arm/libnl.so:system/lib/arm/libnl.so \
    vendor/samsung/santos10wifi/lib/arm/libcamera_metadata.so:system/lib/arm/libcamera_metadata.so \
    vendor/samsung/santos10wifi/lib/arm/libui.so:system/lib/arm/libui.so \
    vendor/samsung/santos10wifi/lib/arm/libaudioresampler.so:system/lib/arm/libaudioresampler.so \
    vendor/samsung/santos10wifi/lib/arm/libnativebridge.so:system/lib/arm/libnativebridge.so \
    vendor/samsung/santos10wifi/lib/arm/libaudioutils.so:system/lib/arm/libaudioutils.so \
    vendor/samsung/santos10wifi/lib/arm/libpixelflinger.so:system/lib/arm/libpixelflinger.so \
    vendor/samsung/santos10wifi/lib/arm/libmediautils.so:system/lib/arm/libmediautils.so \
    vendor/samsung/santos10wifi/lib/arm/libcutils.so:system/lib/arm/libcutils.so \
    vendor/samsung/santos10wifi/lib/arm/libstagefright_yuv.so:system/lib/arm/libstagefright_yuv.so \
    vendor/samsung/santos10wifi/lib/arm/libselinux.so:system/lib/arm/libselinux.so \
    vendor/samsung/santos10wifi/lib/arm/libaudioflinger.so:system/lib/arm/libaudioflinger.so \
    vendor/samsung/santos10wifi/lib/arm/libandroidfw.so:system/lib/arm/libandroidfw.so \
    vendor/samsung/santos10wifi/lib/arm/libwebrtc_audio_coding.so:system/lib/arm/libwebrtc_audio_coding.so \
    vendor/samsung/santos10wifi/lib/arm/libunwind.so:system/lib/arm/libunwind.so \
    vendor/samsung/santos10wifi/lib/arm/libstagefright_foundation.so:system/lib/arm/libstagefright_foundation.so \
    vendor/samsung/santos10wifi/lib/arm/libradio_metadata.so:system/lib/arm/libradio_metadata.so \
    vendor/samsung/santos10wifi/lib/arm/libprocessgroup.so:system/lib/arm/libprocessgroup.so \
    vendor/samsung/santos10wifi/lib/arm/libicui18n.so:system/lib/arm/libicui18n.so \
    vendor/samsung/santos10wifi/lib/arm/libstdc++.so:system/lib/arm/libstdc++.so \
    vendor/samsung/santos10wifi/lib/arm/libandroid.so:system/lib/arm/libandroid.so \
    vendor/samsung/santos10wifi/lib/arm/liblog.so:system/lib/arm/liblog.so \
    vendor/samsung/santos10wifi/lib/arm/libGLESv3.so:system/lib/arm/libGLESv3.so \
    vendor/samsung/santos10wifi/lib/arm/libmedia.so:system/lib/arm/libmedia.so \
    vendor/samsung/santos10wifi/lib/arm/libdl.so:system/lib/arm/libdl.so \
    vendor/samsung/santos10wifi/lib/arm/libvorbisidec.so:system/lib/arm/libvorbisidec.so \
    vendor/samsung/santos10wifi/lib/arm/libsync.so:system/lib/arm/libsync.so \
    vendor/samsung/santos10wifi/lib/arm/libsysutils.so:system/lib/arm/libsysutils.so \
    vendor/samsung/santos10wifi/lib/arm/libnetutils.so:system/lib/arm/libnetutils.so \
    vendor/samsung/santos10wifi/lib/arm/libm.so:system/lib/arm/libm.so \
    vendor/samsung/santos10wifi/lib/arm/libblas.so:system/lib/arm/libblas.so \
    vendor/samsung/santos10wifi/lib/arm/libicuuc.so:system/lib/arm/libicuuc.so \
    vendor/samsung/santos10wifi/lib/arm/libsonic.so:system/lib/arm/libsonic.so \
    vendor/samsung/santos10wifi/lib/arm/libminikin.so:system/lib/arm/libminikin.so \
    vendor/samsung/santos10wifi/lib/arm/libEGL.so:system/lib/arm/libEGL.so \
    vendor/samsung/santos10wifi/lib/arm/libRScpp.so:system/lib/arm/libRScpp.so \
    vendor/samsung/santos10wifi/lib/arm/libGLESv1_CM.so:system/lib/arm/libGLESv1_CM.so \
    vendor/samsung/santos10wifi/lib/arm/libmediandk.so:system/lib/arm/libmediandk.so \
    vendor/samsung/santos10wifi/lib/arm/libwilhelm.so:system/lib/arm/libwilhelm.so \
    vendor/samsung/santos10wifi/lib/arm/libc.so:system/lib/arm/libc.so \
    vendor/samsung/santos10wifi/lib/arm/libft2.so:system/lib/arm/libft2.so \
    vendor/samsung/santos10wifi/lib/arm/libjpeg.so:system/lib/arm/libjpeg.so \
    vendor/samsung/santos10wifi/lib/arm/libutils.so:system/lib/arm/libutils.so \
    vendor/samsung/santos10wifi/lib/arm/libz.so:system/lib/arm/libz.so \
    vendor/samsung/santos10wifi/lib/arm/libandroid_runtime.so:system/lib/arm/libandroid_runtime.so \
    vendor/samsung/santos10wifi/lib/arm/libprotobuf-cpp-lite.so:system/lib/arm/libprotobuf-cpp-lite.so \
    vendor/samsung/santos10wifi/lib/arm/libeffects.so:system/lib/arm/libeffects.so \
    vendor/samsung/santos10wifi/lib/arm/libnativehelper.so:system/lib/arm/libnativehelper.so \
    vendor/samsung/santos10wifi/lib/arm/libETC1.so:system/lib/arm/libETC1.so \
    vendor/samsung/santos10wifi/lib/arm/libimg_utils.so:system/lib/arm/libimg_utils.so \
    vendor/samsung/santos10wifi/lib/arm/libbcc.so:system/lib/arm/libbcc.so \
    vendor/samsung/santos10wifi/lib/arm/libspeexresampler.so:system/lib/arm/libspeexresampler.so \
    vendor/samsung/santos10wifi/lib/arm/libserviceutility.so:system/lib/arm/libserviceutility.so \
    vendor/samsung/santos10wifi/lib/arm/libfilterfw.so:system/lib/arm/libfilterfw.so \
    vendor/samsung/santos10wifi/lib/arm/libcamera_client.so:system/lib/arm/libcamera_client.so \
    vendor/samsung/santos10wifi/lib/arm/libpng.so:system/lib/arm/libpng.so \
    vendor/samsung/santos10wifi/lib/arm/libstagefright_enc_common.so:system/lib/arm/libstagefright_enc_common.so \
    vendor/samsung/santos10wifi/lib/arm/libart.so:system/lib/arm/libart.so \
    vendor/samsung/santos10wifi/lib/arm/libhwui.so:system/lib/arm/libhwui.so \
    vendor/samsung/santos10wifi/lib/arm/libradio.so:system/lib/arm/libradio.so \
    vendor/samsung/santos10wifi/lib/arm/libsqlite.so:system/lib/arm/libsqlite.so \
    vendor/samsung/santos10wifi/lib/arm/libRSCpuRef.so:system/lib/arm/libRSCpuRef.so \
    vendor/samsung/santos10wifi/lib/arm/libnbaio.so:system/lib/arm/libnbaio.so \
    vendor/samsung/santos10wifi/lib/arm/linker:system/lib/arm/linker \
    vendor/samsung/santos10wifi/lib/arm/libcompiler_rt.so:system/lib/arm/libcompiler_rt.so \
    vendor/samsung/santos10wifi/lib/arm/libnetd_client.so:system/lib/arm/libnetd_client.so \
    vendor/samsung/santos10wifi/lib/librtp_jni.so:system/lib/librtp_jni.so \
    vendor/samsung/santos10wifi/lib/libsurfaceflinger_ddmconnection.so:system/lib/libsurfaceflinger_ddmconnection.so \
    vendor/samsung/santos10wifi/lib/libinputservice.so:system/lib/libinputservice.so \
    vendor/samsung/santos10wifi/lib/libhidcommand_jni.so:system/lib/libhidcommand_jni.so \
    vendor/samsung/santos10wifi/lib/libmedialogservice.so:system/lib/libmedialogservice.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_amrwbenc.so:system/lib/libstagefright_soft_amrwbenc.so \
    vendor/samsung/santos10wifi/lib/libRSCpuRef.so:system/lib/libRSCpuRef.so \
    vendor/samsung/santos10wifi/lib/libstagefright_soft_mpeg4enc.so:system/lib/libstagefright_soft_mpeg4enc.so \
    vendor/samsung/santos10wifi/lib/libnbaio.so:system/lib/libnbaio.so \
    vendor/samsung/santos10wifi/lib/libsoftkeymasterdevice.so:system/lib/libsoftkeymasterdevice.so \
    vendor/samsung/santos10wifi/lib/libjni_gallery_jpegstream.so:system/lib/libjni_gallery_jpegstream.so \
    vendor/samsung/santos10wifi/lib/libimage_type_recognition.so:system/lib/libimage_type_recognition.so \
    vendor/samsung/santos10wifi/lib/libpackagelistparser.so:system/lib/libpackagelistparser.so \
    vendor/samsung/santos10wifi/lib/libcompiler_rt.so:system/lib/libcompiler_rt.so \
    vendor/samsung/santos10wifi/lib/libnetd_client.so:system/lib/libnetd_client.so \
    vendor/samsung/santos10wifi/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/samsung/santos10wifi/vendor/lib/hw/memtrack.clovertrail.so:system/vendor/lib/hw/memtrack.clovertrail.so \
    vendor/samsung/santos10wifi/vendor/lib/hw/gps.santos10.so:system/vendor/lib/hw/gps.santos10.so \
    vendor/samsung/santos10wifi/vendor/lib/hw/hwcomposer.clovertrail.so:system/vendor/lib/hw/hwcomposer.clovertrail.so \
    vendor/samsung/santos10wifi/vendor/lib/hw/gralloc.clovertrail.so:system/vendor/lib/hw/gralloc.clovertrail.so \
    vendor/samsung/santos10wifi/vendor/lib/hw/camera.vendor.santos10.so:system/vendor/lib/hw/camera.vendor.santos10.so \
    vendor/samsung/santos10wifi/vendor/lib/libmultidisplay.so:system/vendor/lib/libmultidisplay.so \
    vendor/samsung/santos10wifi/vendor/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/santos10wifi/vendor/lib/libffmpeg_extractor.so:system/vendor/lib/libffmpeg_extractor.so \
    vendor/samsung/santos10wifi/vendor/lib/libmfldadvci.so:system/vendor/lib/libmfldadvci.so \
    vendor/samsung/santos10wifi/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/samsung/santos10wifi/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/samsung/santos10wifi/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/samsung/santos10wifi/vendor/lib/libavcodec.so:system/vendor/lib/libavcodec.so \
    vendor/samsung/santos10wifi/vendor/lib/libmixvbp.so:system/vendor/lib/libmixvbp.so \
    vendor/samsung/santos10wifi/vendor/lib/libavformat.so:system/vendor/lib/libavformat.so \
    vendor/samsung/santos10wifi/vendor/lib/libswresample.so:system/vendor/lib/libswresample.so \
    vendor/samsung/santos10wifi/vendor/lib/libia_aiq.so:system/vendor/lib/libia_aiq.so \
    vendor/samsung/santos10wifi/vendor/lib/libtbd.so:system/vendor/lib/libtbd.so \
    vendor/samsung/santos10wifi/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so \
    vendor/samsung/santos10wifi/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so:system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so \
    vendor/samsung/santos10wifi/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so \
    vendor/samsung/santos10wifi/vendor/lib/libmixvbp_mpeg4.so:system/vendor/lib/libmixvbp_mpeg4.so \
    vendor/samsung/santos10wifi/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/santos10wifi/vendor/lib/libswscale.so:system/vendor/lib/libswscale.so \
    vendor/samsung/santos10wifi/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/samsung/santos10wifi/vendor/lib/libia_mkn.so:system/vendor/lib/libia_mkn.so \
    vendor/samsung/santos10wifi/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/samsung/santos10wifi/vendor/lib/libia_nvm.so:system/vendor/lib/libia_nvm.so \
    vendor/samsung/santos10wifi/vendor/lib/libavutil.so:system/vendor/lib/libavutil.so \
    vendor/samsung/santos10wifi/vendor/lib/libia_aiq_cp.so:system/vendor/lib/libia_aiq_cp.so \
    vendor/samsung/santos10wifi/vendor/lib/libmixvbp_h264.so:system/vendor/lib/libmixvbp_h264.so \
    vendor/samsung/santos10wifi/vendor/lib/libsepdrm.so:system/vendor/lib/libsepdrm.so \
    vendor/samsung/santos10wifi/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/samsung/santos10wifi/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/santos10wifi/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/santos10wifi/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/santos10wifi/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/samsung/santos10wifi/vendor/lib/libffmpeg_utils.so:system/vendor/lib/libffmpeg_utils.so \
    vendor/samsung/santos10wifi/vendor/lib/libffmpeg_omx.so:system/vendor/lib/libffmpeg_omx.so \
    vendor/samsung/santos10wifi/vendor/bin/geomagneticd:system/vendor/bin/geomagneticd \
    vendor/samsung/santos10wifi/vendor/bin/gpsd:system/vendor/bin/gpsd \
    vendor/samsung/santos10wifi/vendor/firmware/fw_sst_08e7.bin:system/vendor/firmware/fw_sst_08e7.bin \
    vendor/samsung/santos10wifi/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd \
    vendor/samsung/santos10wifi/vendor/firmware/bcmdhd_apsta.bin_b2:system/vendor/firmware/bcmdhd_apsta.bin_b2 \
    vendor/samsung/santos10wifi/vendor/firmware/topazsc_fw.bin:system/vendor/firmware/topazsc_fw.bin \
    vendor/samsung/santos10wifi/vendor/firmware/shisp_css15.bin:system/vendor/firmware/shisp_css15.bin \
    vendor/samsung/santos10wifi/vendor/firmware/nvram_net.txt:system/vendor/firmware/nvram_net.txt \
    vendor/samsung/santos10wifi/vendor/firmware/bcmdhd_sta.bin_b2:system/vendor/firmware/bcmdhd_sta.bin_b2
